### ISSUE TITLE
Better Docker workflow 

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#111]
Docker workflow leaves some things to be desired today.

- [x] User should be informed of status re: pulling, crashed container, etc. ... #149
- [x] No `anchor` available in container stuff (#6) #149
- [x] use `anchor` by execing into the validator container (or image, if we're not talking to a local containerized validator) (#6) #149
- [ ] User should be able to toggle local env (i.e., local `solana-test-validator`) vs. Docker exec style?
- [x] Validator run and logs don't communicate their loading status well #149
- [ ] State would not be persisted if validator container needed to be persisted (annoying, because airdrops and accounts would have to be re-created). We need to use a volume here.
- [x] validator logs page will display logs if _any_ local validator is running and the container exists -- this is confusing
- [x] https://github.com/workbenchapp/solana-workbench/issues/107 #149

**Comment by sammanadh** [comment]
I am thinking of moving docker to its own separate global state, so all different conditions (i.e uninstalled, permission deined etc) can be handled in it. It will enable us make sure docker can be used, before attempting to run any containers.

**Comment by nathanleclaire** [comment]
> I am thinking creating a global state for docker, so all different conditions (i.e uninstalled, permission deined etc) can be handled in it. It will enable us make sure docker can be used and warn users, before attempting to run any containers.

Seems reasonable

**Comment by nathanleclaire** [comment]
Yea, to scribble down some additional thoughts / discussion points, I'd like to strive towards smooth integration between the Docker workflow (hopefully also available as a local run as well at $SOME_POINT_IN_FUTURE...), Anchor tests, and Amman.

To elaborate a bit more -- there is a problem setup -- 

1. Amman has its own view of the validator life cycle
2. Workbench has its own view of the validator life cycle (in container)
3. `anchor test` _also_ has its own view of the validator life cycle (it will start a validator on test run)

We could merge these all together in the Workbench --

- Validator start/stop would be managed by Amman in the container (in flight)
- Workbench adds support for selecting an Anchor repo to watch and controlling the validator lifecycle with Anchor's flags to skip things it usually handles (`anchor test --skip-local-validator --skip-build`)

the resulting workflow would then be something like:

- Workbench watches for file changes in an Anchor repo
- On relevant file change, Workbench runs `anchor build` (perhaps exec'd in container)
- Amman config includes the BPF .so from `target/` as a program to include at validator start
- Workbench runs `amman stop`, `amman start` 
- Workbench runs `anchor test --skip-local-validator --skip-deploy --skip-build`

This assumes a desire to wipe persisted validator state each time -- but we could also make it so that anything the user wants to actually keep around gets dropped into the Amman config

**Comment by nathanleclaire** [comment]
bonus -- Anchor doesn't current upload the IDL account automatically on test at the moment (https://github.com/coral-xyz/anchor/issues/1844 ), which is a bit annoying as it's quite helpful decoding what's otherwise gibberish in the explorer -- until upstream adds support for that, we could add it in the loop above (`anchor idl init -f ./target/idls/prog.json <program_pubkey>`)

**Comment by nathanleclaire** [comment]
being able to "import" a repo into workbench for tracking might also help with https://github.com/workbenchapp/solana-workbench/issues/146 cause we could parse `Anchor.toml` etc

**Comment by sammanadh** [comment]
Are you guys planning to replace dockerised validator with anam or give both options to the user?

**Comment by nathanleclaire** [comment]
Dockerized Amman replacing running validator directly yea. @SvenDowideit started  https://github.com/workbenchapp/solana-workbench/pull/149, Sven could you check in with @sammanadh to see how he could be most helpful there?

**Comment by sammanadh** [comment]
hummm... so we will be dockerizing amman..

**Comment by SvenDowideit** [comment]
The POC i did to make sure it wasn't a bad idea, uses `daonetes/solana-amman:v1.10.27` a not optimized docker hub image that has rust, node, solana and amman (and was supposed to have anchor, but that needs work)

@sammanadh would you like to take over #149? What I'm envisioning, is to separate start/stop/remove container (basically the tail) from start/stop/snapshot/restart validator (which would use `docker exec`), and then the log view would use `docker exec validator tail -f /...`

What we want to enable by doing this, is for workbench to generate an ammanrc.json file, created from user selected program ids (from main/dev net), uploaded .so files, and account data that can be pulled in the same way. And then later to add `amman snapshot` save&load.
